server:
  port: 8888
spring:
  application:
    name: marcelo-config-server  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MFreitas98/marcelo-config-server
          #username: username
          #password: password
          default-label: main
          search-paths:
          - 'greeting-service*'  
   